version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.2
  aws-s3: circleci/aws-s3@1.0.0
jobs:
  build:
    executor: aws-cli/default
    steps:
      - checkout
      - run: mkdir bucket && echo "SAMPLE" > bucket/build_asset.txt
      - aws-s3/sync:
          from: bucket
          to: "s3://circleci-application"
          overwrite: true
     
